//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTask { get; set; }
        public int Animal { get; set; }
        public int Medicine { get; set; }
    
        public virtual Animal Animal1 { get; set; }
        public virtual Medicine Medicine1 { get; set; }
    }
}
